stages:
  - test


browser-test-job:
  image: cypress/browsers
  stage: test
  script:
    - npx cypress run --browser chrome 

cypress-include-job:
  stage: test
  image:
    name: cypress/included
    endpoint: [""]
    
  script:
    - npx cypress run --browser chrome 