# GitLab CI/CD for Cypress
stages:
  - test

variables:
  # Skip GitLab's default cache
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - cache/Cypress/

cypress_tests:
  image: cypress/base:14  # Node + Cypress base image
  stage: test
  before_script:
    - npm ci                 # Install dependencies
  script:
    - npx cypress run         # Run all Cypress tests
  artifacts:
    when: always
    paths:
      - cypress/screenshots/  # Save screenshots
      - cypress/videos/       # Save videos
    expire_in: 1 week
