stages:
  - test

cypress_tests:
  image: cypress/browsers:node14.17.0-chrome91-ff89
  stage: test
  before_script:
    - npm ci
    - npx cypress verify      # Verify Cypress installation
  script:
    - npx cypress run --browser chrome --headless
